# version: "3.9"

# services:
#   postgres:
#     image: postgres:15
#     container_name: postgres_db
#     restart: always
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: 1377
#       POSTGRES_DB: SENAT
#     ports:
#       - "5432:5432"
#     volumes:
#       - postgres_data:/var/lib/postgresql/data

#  # pgadmin:
# #   image: dpage/pgadmin4
# #   container_name: pgadmin
# #   restart: always
# #   environment:
# #     PGADMIN_DEFAULT_EMAIL: brunnnolucas@gmail.com
# #     PGADMIN_DEFAULT_PASSWORD: 1377
# #   ports:
# #     - "8080:80"
# #   depends_on:
# #     - postgres

# volumes:
#   postgres_data:
